<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Generate Random Quote</title>
    <link rel="stylesheet" href="../stylesheets/quote.css">


</head>

<body>
    <div class="app">
        <header>Random Quotes</header>
        <section class="quotes">
            <div class="quote-text" id="js-quote-text"></div>
        </section>
        <section class="controls">
            <button type="button" id="js-new-quote" class="new-quote button" onclick="getQuote()">
                Generate a new quote
            </button>
        </section>
    </div>
</body>
<script>
    const newQuoteButton = document.querySelector('#js-new-quote');
    newQuoteButton.addEventListener('click', getQuote);

    const endpoint = 'https://api.quotable.io/random';
    
    
    async function getQuote() {
        // The `try` block executes the statements within it as usual.
        // If an exception is thrown, the statements defined in
        // the `catch` block will be executed.
        // Learn more here: https://javascript.info/try-catch
        try {
            const response = await fetch(endpoint)
            // If the response is not 200 OK...
            if (!response.ok) {
                // ...throw an error. This causes control flow
                // to skip to the `catch` block below.
                throw Error(response.statusText)
            }

            const json = await response.json();
            console.log(json);
        } catch (err) {
            console.log(err)
            alert('Failed to fetch new quote');
        }
    }
</script>

</html>